### ISSUE TITLE
include high and low price for the day after 4:00 pm ET

### ISSUE THREAD

**Issue by BullMarket** [iexg/IEX-API#57] opened 2017-11-03 21:53 UTC
Hello,

First, I really want to thank IEX Group for the free API and I really appreciate your mission to make markets fair for everyone involved. 

I'm looking to get High Low Open Close data for the day after market close (4:00 PM eastern) and I can't find an API call to do so in a clean manner. 

First I looked at https://api.iextrading.com/1.0/stock/AAPL/quote it returns open and close for the day after 4 but I don't see High or Low for the day.

I also tried this call https://api.iextrading.com/1.0/stock/AAPL/previous/ at 5:50 PM ET on 11/03/2017 which does return the High Low data I want but only for the last date (11/02/2017). So if I want High/Low for 11/03/2017 I have to wait till it's past midnight. 

I can call the chart type https://api.iextrading.com/1.0/stock/FLXN/chart/date/20171103 after market close which returns a time series by minute and try to parse it myself but that seems inefficient because it's too much data, extra api call, extra processing time on my end. 

So I'm wondering if you can include High/Low values to quotes type as well? 

Thank you!

**Comment by BullMarket** [comment] 2017-11-03 22:07
I'm sorry. I submitted something that has already been raised as an enhancement multiple times. Should have read older issues before creating more clutter.

Thanks!

**Comment by yccheok** [comment] 2017-11-04 05:56
Hi @BullMarket , a similar request is being submitted at https://github.com/iexg/IEX-API/issues/46

**Comment by evancarter-iex** [comment] 2017-11-06 14:30
Closing as duplicate of https://github.com/iexg/IEX-API/issues/46

**Closed by evancarter-iex** 2017-11-06 14:30 UTC
Labels: duplicate

**Comment by BullMarket** [comment] 2017-11-19 16:36
@evancarter-iex @joshuablackburn-iex Any ideas where we stand on this one in regards to rolling this out in production API? I apologize for asking if this is being tracked elsewhere or already rolled out. I can't find it in the API doc or some other issue where it's referenced. Thanks.
