### ISSUE TITLE
New API: ETFs miss DIV and YIELD info in Stats Endpoint

### ISSUE THREAD

**Issue by bishinew** [iexg/IEX-API#796] opened 2019-03-21 21:11 UTC
## Summary

 ETFs miss DIV, ex-Div Date and YIELD info in Stats Endpoint. These information is available in Stats endpoint for common stocks. The old API works for both common stocks and ETFs.

ttmDividendRate | null
dividendYield | null
exDividendDate | null

Please check and correct it.

### API URL

https://cloud.iexapis.com/beta/stock/market/batch?symbols=VPU,QQQ,VTI&types=stats&token=*

**Comment by evancarter-iex** [comment] 2019-03-23 15:59
Dupe of https://github.com/iexg/IEX-API/issues/654

**Closed by evancarter-iex** 2019-03-23 15:59 UTC
