### ISSUE TITLE
Missing stock symbols

### ISSUE THREAD

**Issue by curtcotner** [iexg/IEX-API#127] opened 2017-12-02 02:03 UTC
## Summary
   I can't seem to get data feeds for all of the stock symbols I track.

### Date/time of issue
12/1/2017  5:56  PM

### API URL
https://api.iextrading.com/1.0/stock/flrux/price
https://api.iextrading.com/1.0/stock/icenx/price
https://api.iextrading.com/1.0/stock/vfinx/price
https://api.iextrading.com/1.0/stock/vwinx/price
https://api.iextrading.com/1.0/stock/bcosx/price
https://api.iextrading.com/1.0/stock/acgyx/price
https://api.iextrading.com/1.0/stock/bxlt/price

### What you expected to happen
Stock quote data.

### What actually happened
Symbol not found.

**Comment by wickman** [comment] 2017-12-02 19:41
I believe this is a duplicate of #16 with the exception of $BXLT which was acquired by $SHPG last year and delisted.

**Comment by jcape** [comment] 2017-12-04 15:37
@curtcotner As @wickman has noted, we don't provide mutual fund data (they aren't exchange-traded products), but we do have an issue open for this, so the best way to track this is on issue #16.

**Closed by jcape** 2017-12-04 15:38 UTC

**Comment by curtcotner** [comment] 2017-12-04 15:41
Thanks!
