### ISSUE TITLE
quotes doesnt handle unknown symbols

### ISSUE THREAD

**Issue by siamoss** [iexg/IEX-API#1044] opened 2019-06-18 22:12 UTC
Hi,

I am downloading OHCL + volume data intraday of >1000 US stocks. I had been using the batch/quotes command before but now its disabled.

now with the new IEX cloud, I use the following request (just 100 symbols instead of 10)
https://cloud.iexapis.com/stable/stock/market/quote?token=xxx&symbols=A,AA,AAAP,AAAU,AABA,AAC,AADR,AAL,AAMC,AAME

unfortunately, the request returns bad "Unknown symbol" because one of the symbols is invalid (AAAP). Before the API could handle old symbols and just didnt return values for it, but only the ones that exist.

1.) It would be good if the API handled this case.

2.) I know I can varify my stocks list with the ref-data request. However, I have to do this each time I request all data or I have to also save this list non volatile and then I have the risk of "what if" which needs to be handled too othervise I may lose the data of 100 stocks 
https://cloud.iexapis.com/stable/ref-data/iex/symbols?token=xxx

**Comment by StockConsultant** [comment] 2019-06-29 00:32
I mentioned this problem back before the switch over, You have to use the batch endpoint for for IEX cloud to handle unknown symbols.

**Comment by evancarter-iex** [comment] 2019-11-03 01:04
Dupe of #956

**Closed by evancarter-iex** 2019-11-03 01:04 UTC
Labels: IEX Cloud, Type: data, Type: issue
