### ISSUE TITLE
Several symbols show SIP quote as late as 7:30p

### ISSUE THREAD

**Issue by McQgit** [iexg/IEX-API#274] opened 2018-03-26 23:34 UTC
## Summary
Most quotes for stock symbols show a calculationPrice type of "close" by 4:30p (often a bit earlier).  Today I saw several symbols which show "sip" instead at 4:30p and still as late as 7:30pm.

## Details
No further details needed (?)

### Date/time of issue
Mon Mar26 2018 at 7:30pm eastern

### API URL
https://api.iextrading.com/1.0/stock/market/batch?symbols=mcd,itw&types=quote,previous,ohlc

### What you expected to happen
These quotes to show "Close" as the calculationPrice

### What actually happened
    [quote] => Array
        (
            [symbol] => MCD
            [companyName] => McDonald's Corporation
            [primaryExchange] => New York Stock Exchange
            [sector] => Consumer Cyclical
            [calculationPrice] => sip
            [open] => 156.21
            [openTime] => 1522071000465
            [close] => 154.98
            [closeTime] => 1521835236992
            [high] => 158.2
            [low] => 156.21
            [latestPrice] => 158.01
            [latestSource] => 15 minute delayed price
            [latestTime] => 4:56:11 PM
            [latestUpdate] => 1522097771008
            [latestVolume] => 3476004
            [iexRealtimePrice] => 157.99
            [iexRealtimeSize] => 50
            [iexLastUpdated] => 1522094396029
            [delayedPrice] => 158.01
            [delayedPriceTime] => 1522097771008
            [previousClose] => 154.98
            [change] => 3.03
            [changePercent] => 0.01955
            [iexMarketPercent] => 0.01917
            [iexVolume] => 66635
            [avgTotalVolume] => 5569600
            [iexBidPrice] => 0
            [iexBidSize] => 0
            [iexAskPrice] => 0
            [iexAskSize] => 0
            [marketCap] => 125538610019
            [peRatio] => 23.69
            [week52High] => 178.7
            [week52Low] => 128.6
            [ytdChange] => -0.099639228262196
        )

    [previous] => Array
        (
            [symbol] => MCD
            [date] => 2018-03-23
            [open] => 157.59
            [high] => 158.08
            [low] => 154.92
            [close] => 154.98
            [volume] => 3447383
            [unadjustedVolume] => 3447383
            [change] => -2.06
            [changePercent] => -1.312
            [vwap] => 156.3903
        )

    [ohlc] => Array
        (
            [open] => Array
                (
                    [price] => 156.21
                    [time] => 1522071000465
                )

            [close] => Array
                (
                    [price] => 154.98
                    [time] => 1521835236992
                )

            [high] => 158.2
            [low] => 156.21
        )

### Other Information (sample code, links, etc.)
n/a

**Comment by McQaws** [comment] 2018-03-27 00:44
The quote info gets worse.  Around 8pm eastern the status changed from 'sip' to 'previousclose' but the previousclose figures are as of last Fri - not today.  Thus, there is no way to determine today's closing price from the current quote info.

Here is the results of the same api, including previousClose and OHLC as I showed at the top but this is now 8:35pm eastern:

{
  "MCD": {
    "quote": {
      "symbol": "MCD",
      "companyName": "McDonald's Corporation",
      "primaryExchange": "New York Stock Exchange",
      "sector": "Consumer Cyclical",
      "calculationPrice": "previousclose",
      "open": 156.21,
      "openTime": 1522071000465,
      "close": 154.98,
      "closeTime": 1521835236992,
      "high": 158.2,
      "low": 156.21,
      "latestPrice": 154.98,
      "latestSource": "Previous close",
      "latestTime": "March 23, 2018",
      "latestUpdate": 1521763200000,
      "latestVolume": 3476004,
      "iexRealtimePrice": 157.99,
      "iexRealtimeSize": 50,
      "iexLastUpdated": 1522094396029,
      "delayedPrice": 158.01,
      "delayedPriceTime": 1522097771008,
      "previousClose": 154.98,
      "change": 0,
      "changePercent": 0,
      "iexMarketPercent": 0.01917,
      "iexVolume": 66635,
      "avgTotalVolume": 5569600,
      "iexBidPrice": 0,
      "iexBidSize": 0,
      "iexAskPrice": 0,
      "iexAskSize": 0,
      "marketCap": 123131281442,
      "peRatio": 23.24,
      "week52High": 178.7,
      "week52Low": 128.6,
      "ytdChange": -0.09963922826219572
    },
    "previous": {
      "symbol": "MCD",
      "date": "2018-03-23",
      "open": 157.59,
      "high": 158.08,
      "low": 154.92,
      "close": 154.98,
      "volume": 3447383,
      "unadjustedVolume": 3447383,
      "change": -2.06,
      "changePercent": -1.312,
      "vwap": 156.3903
    },
    "ohlc": {
      "open": {
        "price": 156.21,
        "time": 1522071000465
      },
      "close": {
        "price": 154.98,
        "time": 1521835236992
      },
      "high": 158.2,
      "low": 156.21
    }
  },
  "ITW": {
    "quote": {
      "symbol": "ITW",
      "companyName": "Illinois Tool Works Inc.",
      "primaryExchange": "New York Stock Exchange",
      "sector": "Industrials",
      "calculationPrice": "previousclose",
      "open": 160.14,
      "openTime": 1522071000506,
      "close": 156.91,
      "closeTime": 1521835328014,
      "high": 160.63,
      "low": 156.4,
      "latestPrice": 156.91,
      "latestSource": "Previous close",
      "latestTime": "March 23, 2018",
      "latestUpdate": 1521763200000,
      "latestVolume": 1509899,
      "iexRealtimePrice": 159.99,
      "iexRealtimeSize": 20,
      "iexLastUpdated": 1522094397554,
      "delayedPrice": 160.01,
      "delayedPriceTime": 1522097771008,
      "previousClose": 156.91,
      "change": 0,
      "changePercent": 0,
      "iexMarketPercent": 0.0198,
      "iexVolume": 29896,
      "avgTotalVolume": 1520131,
      "iexBidPrice": 0,
      "iexBidSize": 0,
      "iexAskPrice": 0,
      "iexAskSize": 0,
      "marketCap": 53591938768,
      "peRatio": 23.74,
      "week52High": 179.07,
      "week52Low": 129.17,
      "ytdChange": -0.05058389302353732
    },
    "previous": {
      "symbol": "ITW",
      "date": "2018-03-23",
      "open": 163.06,
      "high": 164.03,
      "low": 156.67,
      "close": 156.91,
      "volume": 1898664,
      "unadjustedVolume": 1898664,
      "change": -5.84,
      "changePercent": -3.588,
      "vwap": 159.2157
    },
    "ohlc": {
      "open": {
        "price": 160.14,
        "time": 1522071000506
      },
      "close": {
        "price": 156.91,
        "time": 1521835328014
      },
      "high": 160.63,
      "low": 156.4
    }
  }
}

Note I previously reported #222 for similar problem but you can close that one as a duplicate of this.  The description I am providing with this one (274) is much clearer and better documented.  Thanks.

**Comment by McQaws** [comment] 2018-03-27 04:16
Between 11pm Mon Mar26 and midnight the quote now shows the calculationPrice of 'close'.  However, the latestTime in the /quote section is still Fri Mar23.  The latest price and previous price properly show Mon and Fri close values, respectively.   Note the timestamp in the /previous data is for Mon Mar26 which is normally what I see by midnight.

So, this data largely looks correct now except for the wrong date in the /quote.  But, waiting 7-8 hours to see the day's closing price is unusually long.

This pattern on Mar26 was unique to 3 symbols out of about 50 that I checked.  Below is the same api results as above - just from a few minutes after midnight (very early AM Tue Mar27 now).

{
  "MCD": {
    "quote": {
      "symbol": "MCD",
      "companyName": "McDonald's Corporation",
      "primaryExchange": "New York Stock Exchange",
      "sector": "Consumer Cyclical",
      "calculationPrice": "close",
      "open": 156.21,
      "openTime": 1522071000465,
      "close": 158.01,
      "closeTime": 1521835236992,
      "high": 158.2,
      "low": 156.21,
      "latestPrice": 158.01,
      "latestSource": "Close",
      "latestTime": "March 23, 2018",
      "latestUpdate": 1521835236992,
      "latestVolume": 3476004,
      "iexRealtimePrice": 157.99,
      "iexRealtimeSize": 50,
      "iexLastUpdated": 1522094396029,
      "delayedPrice": 158.01,
      "delayedPriceTime": 1522097771008,
      "previousClose": 154.98,
      "change": 3.03,
      "changePercent": 0.01955,
      "iexMarketPercent": 0.01917,
      "iexVolume": 66635,
      "avgTotalVolume": 5569600,
      "iexBidPrice": 0,
      "iexBidSize": 0,
      "iexAskPrice": 0,
      "iexAskSize": 0,
      "marketCap": 125538610019,
      "peRatio": 23.69,
      "week52High": 178.7,
      "week52Low": 128.6,
      "ytdChange": -0.08203635603116237
    },
    "previous": {
      "symbol": "MCD",
      "date": "2018-03-26",
      "open": 156.21,
      "high": 158.2,
      "low": 156.21,
      "close": 158.01,
      "volume": 3476951,
      "unadjustedVolume": 3476951,
      "change": 3.03,
      "changePercent": 1.955,
      "vwap": 157.3902
    },
    "ohlc": {
      "open": {
        "price": 156.21,
        "time": 1522071000465
      },
      "close": {
        "price": 154.98,
        "time": 1521835236992
      },
      "high": 158.2,
      "low": 156.21
    }
  },
  "ITW": {
    "quote": {
      "symbol": "ITW",
      "companyName": "Illinois Tool Works Inc.",
      "primaryExchange": "New York Stock Exchange",
      "sector": "Industrials",
      "calculationPrice": "close",
      "open": 160.14,
      "openTime": 1522071000506,
      "close": 160.01,
      "closeTime": 1521835328014,
      "high": 160.63,
      "low": 156.4,
      "latestPrice": 160.01,
      "latestSource": "Close",
      "latestTime": "March 23, 2018",
      "latestUpdate": 1521835328014,
      "latestVolume": 1509899,
      "iexRealtimePrice": 159.99,
      "iexRealtimeSize": 20,
      "iexLastUpdated": 1522094397554,
      "delayedPrice": 160.01,
      "delayedPriceTime": 1522097771008,
      "previousClose": 156.91,
      "change": 3.1,
      "changePercent": 0.01976,
      "iexMarketPercent": 0.0198,
      "iexVolume": 29896,
      "avgTotalVolume": 1520131,
      "iexBidPrice": 0,
      "iexBidSize": 0,
      "iexAskPrice": 0,
      "iexAskSize": 0,
      "marketCap": 54650730497,
      "peRatio": 24.21,
      "week52High": 179.07,
      "week52Low": 129.17,
      "ytdChange": -0.03182670781146015
    },
    "previous": {
      "symbol": "ITW",
      "date": "2018-03-26",
      "open": 160.14,
      "high": 160.63,
      "low": 156.4,
      "close": 160.01,
      "volume": 1510107,
      "unadjustedVolume": 1510107,
      "change": 3.1,
      "changePercent": 1.976,
      "vwap": 158.6919
    },
    "ohlc": {
      "open": {
        "price": 160.14,
        "time": 1522071000506
      },
      "close": {
        "price": 156.91,
        "time": 1521835328014
      },
      "high": 160.63,
      "low": 156.4
    }
  }
}

**Closed** 2019-02-08 20:16 UTC
Labels: Needs: investigation
