### ISSUE TITLE
Mutual fund support

### ISSUE THREAD

**Issue by romelusw** [iexg/IEX-API#16] opened 2017-09-14 14:12 UTC
Would it be possible to provide support for mutual fund securities?

**Comment by ynagorny** [comment] 2017-11-06 03:11
I just wanted to add that I am also looking forward to adding support for mutual funds if it is at all possible.

**Comment by joshuablackburn-iex** [comment] 2017-11-06 11:23
We are looking into sourcing this data.  We will keep you updated if it is something we can get added to the API.

**Comment by dgwieland** [comment] 2017-11-09 21:33
Piling on here.  I also want to request support for mutual fund data.

**Comment by tboooe** [comment] 2017-11-10 18:54
Yes please...hopefully with an update time around 4pm PST like Yahoo and other investment houses (used to) do.  Other options update closing mutual fund prices at around 8-9pm PST.

**Comment by bishinew** [comment] 2017-11-19 01:08
Please add Mutual Fund end of day quote. Many thanks

**Comment by rt999** [comment] 2017-11-20 02:25
I would also like to request support for Mutual Fund data.  Thanks in advance.

**Comment by evancarter-iex** [comment] 2017-11-20 14:01
Locking until we find a data source. If you are interested in this feature, please add a 👍  to the first comment.

**Closed** 2019-02-08 19:27 UTC
Labels: IEX Cloud, Resolution: deployed, Resolution: moving to IEX Cloud

**Comment by evancarter-iex** [comment] 2019-02-08 19:29
Mutual Funds are now supported in IEXCloud.  Sign up for beta access, if you havent already. 

https://iexcloud.io/

**Comment by rschnapp** [comment] 2022-04-06 23:25
...so, I've been using IEX to get stock and mutual fund data for a couple of years now. As of today (April 6, 2022), I'm finding that mutual fund data aren't being delivered. No error message. Status page shows no problems. And the /ref-data/mutual-funds/symbols endpoint still shows support for all the mutual fund tickers I'm requesting.

I don't have a paid account, so I have no way of asking IEX Cloud what's going on...
...I assume I'm not the only one seeing this?

**Comment by rsaldinger** [comment] 2022-04-06 23:49
@rschnapp Same here! I started seeing this last week: the "previous" endpoint would return a 404 for any mutual fund symbol I tried (even though the same endpoint still worked for stock and ETF symbols). Oddly, last week it returned "404 Not Found," whereas today it returns "404 Unknown symbol" (not sure if that *means* anything but something did change).

The "chart" endpoint stopped returning any data after March 29th, but doesn't return an error (just an empty result if you don't go back that far).

I'm also on the free plan. I thought maybe mutual fund data got dropped from the free tier, but could not find no announcement or anything. (Interestingly, when I tried the "ohlc" endpoint, which is documented as available only on paid plans, it still returns 404 on a mutual fund symbol but "402 The requested data is not available to free tier accounts" on a stock symbol...)

**Comment by agrberg** [comment] 2022-04-11 15:49
😭 I'm experiencing the same issue as well FWIW. Would love to get mutual funds back as it's necessary for my users.

**Comment by rschnapp** [comment] 2022-04-11 19:13
Bad news: I managed to submit a support request to IEX Cloud. They confirmed that mutual fund data had to be disabled because of "upstream compliance" issues. Presumably, that means there's some contractual limitation that they need to avoid violating. They're looking into alternatives, but there's no guarantees on "if" or "when".

Sigh. Off to investigate alternate API providers. What a shame. IEX is so clean and efficient and easy to use!

**Comment by agrberg** [comment] 2022-04-11 19:47
Thank you for the update @rschnapp 🙇 Echo the bad news though. I've really enjoyed working w/ IEX's API and have even contributed to the Ruby gem because it's so useful to me.

Let us know if you find any reasonable alternatives while this remains a product gap.

**Comment by rschnapp** [comment] 2022-04-12 01:32
I think I'm just going to run a cronjob to use the AlphaVantage API in the evening. I'll capture all the NAVs and store them in a file to be used during my daytime portfolio updates. That's more efficient anyway -- I hadn't been distinguishing between stocks/ETFs and mutual funds, which means I was always getting the same NAV price for the mutual funds throughout the day. This will  cut down on traffic.

I only hope that AlphaVantage is more reliable now than they had been a couple of years ago, when I finally gave up on them and ported to IEX cloud.

**Comment by agrberg** [comment] 2022-04-13 14:48
This won't work for my SaaS application but I've been able to make my personal spreadsheets (Google Sheets) work with the `GOOGLEFINANCE` method ([docs](https://support.google.com/docs/answer/3093281?hl=en))

**Comment by cgailey** [comment] 2022-04-13 19:41
EOD Historical Data (https://eodhistoricaldata.com/financial-apis/api-for-historical-data-and-volumes/) is an alternative for US Mutual Fund data.
