### ISSUE TITLE
Different Time Frames

### ISSUE THREAD

**Issue by Investingclarity** [iexg/IEX-API#1687] opened 2021-01-20 02:16 UTC
### Please keep all posted issues professional and constructive. We may delete posts that do not provide sufficient information, are outright negative and unproductive, or are not directly related to IEX Cloud.

**Email account associated with your IEX Account**
investingclarity@gmail.com

**Is your feature request related to a problem? Please describe.**
It's not a problem.

**Describe the solution you'd like**
I would like to have parameters that aggregate the data being sent back by the API. I found the option "chartInterval" parameter but unfortunately, it doesn't aggregate data in Nth days. It would be really helpful, if there was a parameter that took in the values "w" and "m" to return the data in weekly time frame and monthly time frame.

**Describe alternatives you've considered**
Aggregating the data through code. 

**Additional context**
Aggregating data makes everything harder especially if your new to coding, such as my self. I am able to aggregate the data from daily to weekly and monthly. However, for weeks where there are only say, 4 trading days, my aggregation of weekly data can't distinguish a 4 day trading week vs a 5 day trading week and this impacts back testing.

**Comment by McQgit** [comment] 2021-01-20 03:15
@Investingclarity I am not IEX nor do I have a specific solution.  I wanted to offer for your consideration that the markets have closed for unusual cases apart from holidays.  For example, after 9/11 markets were closed more than a week.  Last year, markets closed for parts of the day due to circuit breakers.  These are just a couple examples.

There are also recurring, but irregular, half-day holidays making a 'week' just 4.5 days.

Given all the various circumstances, I think it would be difficult for anyone to create a single aggregation that would satisfy everyone.  Someone who only cared about prices might view it one way.  If you were looking at volumes that's a different thing yet.

Here's background on unusual closures:
https://www.thestreet.com/video/market-halts-closure-coronavirus-history

Current market holidays and half-days:
https://www.nyse.com/markets/hours-calendars

It's unlikely to be of concern, but, there are also two US banking holidays that delay trade settlements (and impact dividend ex-div dates) where the markets are otherwise open.  These are Veteran's day and Columbus day.
https://www.federalreserve.gov/aboutthefed/k8.htm

**Comment by Investingclarity** [comment] 2021-01-20 03:38
@McQgit I totally agree. There are various reasons for a market to not have data from Monday - Friday, as you have pointed out. All the more reason for IEX-API to provide a parameter that allows customers to gather data from their database - which, would already that already satisfy all the reasons why data might be less than Monday - Friday. I think this is the most efficient way, rather than everyone aggregating data on their own. Thank you for your insight.

**Comment by McQgit** [comment] 2021-01-20 04:24
@Investingclarity I thought your concern was knowing when it was a 4-day vs a 5-day week as it affected your back-testing.  I was pointing out other situations that affected trading hours so you could incorporate that in your thinking on how to handle those situations - even some days being only half-days or otherwise had limited trading hours.  I think I misunderstood - never mind.

**Comment by Investingclarity** [comment] 2021-01-20 04:59
@McQgit You haven't misunderstood. In this specific situation, concerning a specific dataset of a certain stock symbol, I need to implement in my function a way to check when a certain week is a 4-day week and aggregate accordingly compared to the majority of the 5-day weeks, which end on Friday. But the bigger issue, is all the reasons that a stock might not be a 5-day week, all the reasons you have pointed out. For that reason, it becomes really difficult trying to implement code to check if a week trades from Monday to Tuesday, with Wednesday being a holiday, then, trading again from Thursday to Friday. Compared to another week in another month where, the week had only 3-day trading week. Vs. another unexpected market closure such as 911, vs all the other holidays etc... etc...

If IEX CLOUD implements a parameter on their side that will provide data in different time frames such as, weekly, monthly etc.., we wouldn't have to implement code that checks for what I mentioned above because, the data we get from IEX CLOUD will have been filtered for data only available for trading days. For example, If you make an API call with a parameter that allows you to retrieve that data in say, weekly time frame. If a certain week only had 3 days of trading, you could see that in the date column of your dataframe

For example:

index   date             open  high   low    close    
-------------------------------------------------
102     2021-01-01   8.22   6.70   6.82   7.71
103     2021-01-05   7.72   6.58   7.44   7.57 --------This week only had 3 trading days.
104     2021-01-15   9.74   7.07   9.50   7.35

vs. resampling it with code.

index   date             open  high   low    close    
-------------------------------------------------
102     2021-01-01   8.22   6.70   6.82   7.71
103     2021-01-08   7.72   6.58   7.44   7.57--------Even though this week was 3 trading days, it shows the closing date as
104     2021-01-15   9.74   7.07   9.50   7.35            2021-01-08, which ends on a Friday. This is because my resample function
                                                                                takes daily data and resamples it to weekly, with weeks ending on Fridays.
                                                                                Because, 99% of all the other trading weeks end on a Friday. So, what I am
                                                                                trying to say is that, if I were to do it with code, I would have to take into
consideration all the weeks that are not 5 full trading days, holidays, and all the other reasons. For this reason, it would be so
helpful if IEX CLOUD just provided us with a parameter we can use to retrieve the data in a certain time-frame. Sorry for over
explaining but, I figure this would get my point across.

**Comment by Investingclarity** [comment] 2021-03-17 01:50
This company hasn't replied back to this issue or anything... Short of staff or what's going on here?

**Comment by timpaine-iex** [comment] 2021-03-17 13:12
@Investingclarity response time is prioritized by account type. SLA is available on the pricing page (https://iexcloud.io/pricing/).

**Comment by timpaine-iex** [comment] 2021-04-28 21:41
closing as a duplicate of https://github.com/iexg/IEX-API/issues/221

**Closed by timpaine-iex** 2021-04-28 21:41 UTC
Labels: IEX Cloud, Type: enhancement request
