### ISSUE TITLE
[Request] Historic key stats

### ISSUE THREAD

**Issue by para2x** [iexg/IEX-API#912] opened 2019-04-30 01:51 UTC
**Is your feature request related to a problem? Please describe.**
Well... I'd like to first thank the IEX team for offering such a great service. 
I was wondering if anybody knows if this feature exist or not or if IEX plans to add that at some point. 

**Describe the solution you'd like**
I'd like to get access to historic key starts like marketcap, avgVolume, EPS, and etc.

**Describe alternatives you've considered**

**Additional context**

**Comment by timpaine-iex** [comment] 2021-03-01 18:35
duplicate of https://github.com/iexg/IEX-API/issues/507

**Closed by timpaine-iex** 2021-03-01 18:35 UTC
Labels: IEX Cloud, Type: enhancement request
