### ISSUE TITLE
[Data] Market Cap missing from SHY in IEX Cloud

### ISSUE THREAD

**Issue by dylanitorium** [iexg/IEX-API#967] opened 2019-05-20 02:44 UTC
**Clearly describe the data problem**
The `marketcap` value is missing from `SHY` in IEX Cloud (v1/stable) but is present in IEX Trading API

**Data URL (The URL you used to access the data without your token):**
https://cloud.iexapis.com/stable/stock/shy/batch?types=quote
https://cloud.iexapis.com/stable/stock/shy/quote

https://api.iextrading.com/1.0/stock/SHY/quote
https://api.iextrading.com/1.0/stock/SHY/batch?types=quote

**What time did the problem occur (including timezone)?**
2:40PM NZST

**What is the expected behavior?**
The `marketcap` to be present in IEX Cloud if it is present in the IEX Trading API

**What are the steps to reproduce**
Visit the data url.

**Your environment (e.g. browser, OS, API version, language):**
Chrome 74.0.3729.131, Mac 10.14.3, v1, N/A

**Additional context**
IEX Cloud Grow Plan.

We are 10 days away from IEX Trading API being sunsetted and we are working to get the migration production ready.

**Comment by evancarter-iex** [comment] 2019-05-20 13:38
@dylanitorium Thanks, this is a dupe of #855 We are working through an integration with our data provider for additional information on ADRs and ETFs

**Closed by evancarter-iex** 2019-05-20 13:38 UTC
Labels: IEX Cloud, Type: data
