### ISSUE TITLE
Google Sheets doesn't set HTTP `Referer` header.

### ISSUE THREAD

**Issue by agrberg** [iexg/IEX-API#1524] opened 2020-07-04 18:35 UTC
# `2020-07-04T19:00:00Z`

## Setup
I set `*.google.com` as a domain restriction for for my publishable token.
After waiting a few minutes I use `=IMPORTDATA("https://cloud.iexapis.com/v1/stock/" & A7 & "/quote/latestPrice?token=pk_1111111111111")` in Google Sheets.

## Expectations
I expect it to return the latest price of the stock symbol in cell `A7` which is `"VTI"`.
Instead it returns an error that it cannot be loaded.

## Additional Information
This worked without problem before I set the domain restriction at `https://iexcloud.io/console/tokens`. My guess is that either Google Sheets doesn't set the `Referer` HTTP header or it is set to something that doesn't match `*.google.com`.

I cannot see the request in the Network tab of the web inspector as it sends it through Google via a call with a `fetchData` endpoint.

**Comment by timpaine-iex** [comment] 2020-12-16 16:02
@agrberg I can confirm that sheets requests seem to come from `sheets.google.com`, though I didn't dig into the contents of the request. I will make a note to try to dig in a little further, in the mean time you may be able to workaround by whitelisting the IPs or maybe `sheets.google.com` directly will work. Depending on the potentially circuitous route the requests come out of google's plant, it might trip things up.

Alternatively, the publishable key's are designed to be publishable, so there's nothing inherently "wrong" about keeping it unrestricted.

**Comment by agrberg** [comment] 2020-12-16 16:23
Thanks for the update @timpaine-iex. Please let me know when you find out more. I'll give `sheets.google.com` a try. If that works I believe it would indicate that there's problem with the wildcard as `*.google.com` was not working when I originally tried this.

**Comment by timpaine-iex** [comment] 2020-12-16 16:36
@agrberg no problem, let me know what you find and I'll make sure we track internally

**Comment by agrberg** [comment] 2020-12-23 16:47
@timbaker-iex Hey Tim! Sorry for the delay. I've updated the the domain for my publishable token as in the screenshot to `sheets.google.com` and can confirm that it is not working as intended.

![token](https://user-images.githubusercontent.com/410469/103018526-07a2d200-450b-11eb-9599-fabdd21ea059.png)

When I go to my Google Sheet for my portfolio, all of the cells that make an API call to IEX fail with `#N/A` in the cell and the following error message on hover (redactions mine):

> Could not fetch url: https://cloud.iexapis.com/v1/stock/VTI/quote/latestPrice?token=pk_XXXXXXXXXXXX

I've since removed the domain and am waiting for it to work again.

I _can_ confirm that the functionality does work in some cases. For example when using the [`iex-ruby-client`](https://rubygems.org/gems/iex-ruby-client) library I can restrict access to the domain set in the HTTP `Referer` header. This functionality has [since been incorporated into the library](https://github.com/dblock/iex-ruby-client/commit/ca706ff32adf020e90ed66fec5fcd9a2da4dd0a9#diff-cba635b307d1b746cd3dd58d3b00676ea72c67e901921ef390b70ad511936bffR18).

My best guess at this point is that there is an additional check happening where perhaps the IP or one of the `X-Forwarded-For` IPs are being checked against the actual domain being listed to confirm that they line up as there's nothing preventing me from setting this header to whatever string I'd like. However this is simply the best guess I have at the moment. I'm more of an application engineer than an infrastructure or networking one. I learned about the `Referer` header and its historical misspelling when I discovered this feature with IEX.

**Comment by timpaine-iex** [comment] 2020-12-28 15:03
@agrberg will take a closer look, we have an open ticket to track this. Unfortunately some of these things aren't standard (e.g. look at [the docs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For) for `X-Forwarded-For`, its a "de-facto" standard not an actual standard, and one always needs to be wary of which elements can be spoofed).

**Comment by agrberg** [comment] 2020-12-28 16:12
Thanks Tim. ☝️ that's exactly how I feel about `Referer`. I can set it to whatever I realistically want even if it is not my domain. Without knowing nearly as much about networking as many do I imagine there are multiple ways and maybe only few best practices to "confirm" the `Referer` header actually points to the domain it claims it came from 🤷‍♂️

**Comment by timkpaine** [comment] 2020-12-28 21:28
Here's what I get from sheets
```
X-Real-Ip 64.233.172.102
Host <my host>
X-Forwarded-For 64.233.172.102
X-Forwarded-Proto https
Connection upgrade
Origin http://<my host>
User-Agent Mozilla/5.0 (compatible; GoogleDocs; apps-spreadsheets; +http://docs.google.com)
Accept-Encoding gzip,deflate,br
```

**Comment by timkpaine** [comment] 2020-12-28 21:31
so not only do they not set `referer`, the `X-Forwarded-For` header is any of the originating google servers

**Comment by timkpaine** [comment] 2020-12-28 22:06
Ok here's how I worked around. Since `IMPORTDATA` doesn't expose this I needed to go an app script (this would be a good project to turn into a standalone library!)

Added a script to my sheet:
![Screen Shot 2020-12-28 at 16 49 58](https://user-images.githubusercontent.com/3105306/103245698-f43e9f00-492e-11eb-8e4e-d45c3faac9d3.png)

Filled in the code making sure to set the header
```javascript
function test() {
  // get spreadsheet
  var ss = SpreadsheetApp.getActiveSpreadsheet();

  // get first sheet in list
  var sheet = ss.getSheets()[0];

  // set url
  var url = 'https://cloud.iexapis.com/stable/stock/BAC/company?token=pk_...';

  // request from iex but setting header
  var response = UrlFetchApp.fetch(url, {'headers': {'referer': 'sheets.google.com'}});

  // parse into json
  var json = JSON.parse(response.getContentText());

  // Prepare to fill cells
  var cells = sheet.getRange('A1:B' + Object.keys(json).length);

  // fill with data
  cells.setValues(Object.entries(json));
}
```

And voilà

![Screen Shot 2020-12-28 at 17 04 25](https://user-images.githubusercontent.com/3105306/103245724-0d475000-492f-11eb-8eed-92d4311e154d.png)

**Comment by timpaine-iex** [comment] 2020-12-28 22:14
Closing as we can't really work around this right now, however definitely interested if someone is working on an Apps Script library to handle this functionality

**Closed by timpaine-iex** 2020-12-28 22:14 UTC
Labels: IEX Cloud
