### ISSUE TITLE
Stock Beta Value

### ISSUE THREAD

**Issue by kbeck1** [iexg/IEX-API#824] opened 2019-03-29 17:59 UTC
## Summary
The old API had the beta value of a stock available under key stats. I noticed that this value is not available under the new cloud API?

### Date/time of issue
March 29,2019

### API URL

https://cloud.iexapis.com/beta/stock/AAPL/stats/beta?token=xxxxxxx

### What you expected to happen

Return the beta value of a stock

### What actually happened

Data doesn't exist

### Other Information (sample code, links, etc.)

https://api.iextrading.com/1.0/stock/AAPL/stats/beta

**Comment by evancarter-iex** [comment] 2019-03-30 22:36
Duplicate of this https://github.com/iexg/IEX-API/issues/740

**Closed by evancarter-iex** 2019-03-30 22:36 UTC
