### ISSUE TITLE
New API IEX Cloud: International Stock Support

### ISSUE THREAD

**Issue by bishinew** [iexg/IEX-API#702] opened 2019-02-21 21:47 UTC
## Summary
Do you plan to provide the delay quote from the major international markets?
When will this feature be available?

**Comment by joshuablackburn-iex** [comment] 2019-02-22 10:16
Yes. We are working on the legal side for delayed quotes. We should have EOD prices much sooner than that, with the following exchanges being the first group:


Euronext Amsterdam
Berlin Stock Exchange
Euronext Brussels
Euronext Dublin
Dusseldorf Stock Exchange
XETRA
Frankfurt Stock Exchange
Hamburg Stock Exchange
Euronext Lisbon
London Stock Exchange
Munich Stock Exchange
Euronext Paris
Stuttgart Stock Exchange
Abu Dhabi Securities Exchange
BSE Ltd.
Korea Exchange
Tel Aviv Stock Exchange

**Comment by lars670** [comment] 2019-02-22 11:20
This is good to hear, and I am sure that you are aware that for the European Union (EU) a legal directive called Mifid/Mifir, which took effect Jan. 2018 states that all exchanges within the EU should on their website publish delayed data no later than 15 minutes for all traded instruments (Implicit also EOD) This should be done for free/Symbolic price and in a structured and documented way - Free for everyone to use or redistribute.

**Comment by 3vian** [comment] 2019-02-26 15:35
Other than price, what data are you planning to provide? corporate actions? fundamentals?

**Comment by mortenc** [comment] 2019-02-27 07:24
@joshuablackburn-iex This is great news, thanks for the update! 

Any chance you could tell us what other exchanges are on your roadmap? I'm building a product that needs support for Scandinavian stocks, namely Copenhagen Stock Exchange (Nasdaq Copenhagen) and Stockholm Stock Exchange (Nasdaq Stockholm). Not knowing if that data will become available is the primary thing keeping me from going all in on IEX Cloud for the product.

**Comment by Amosss** [comment] 2019-03-01 10:14
Following this discussion, specially regarding @3vian 's question

**Comment by weedstreet420** [comment] 2019-03-03 07:15
Will you have delayed data from the CSE Composite (Canadian Stock Exchange)?

**Comment by evancarter-iex** [comment] 2019-03-07 20:39
Duplicate of #51

**Closed by evancarter-iex** 2019-03-07 20:39 UTC
Labels: IEX Cloud, Roadmap: in development, Type: data

**Comment by ws420** [comment] 2019-09-14 20:30
Maybe if you answered the question I wouldn't have to create duplicates.
IEX support is non-existent.

**Comment by flyingbrike** [comment] 2020-04-15 07:45
Is there already support for European markets?

**Comment by ws420** [comment] 2020-08-13 21:55
Any update on this?

When will you support CSE stocks like all of the other competitors' APIs?

I asked the same question 1 year ago, still no news ...............

**Comment by joshuablackburn-iex** [comment] 2020-08-13 22:19
We are in the process of adding 50+ markets and loads more data. Big updates on the way.

**Comment by michaelBielang** [comment] 2020-12-25 16:13
When pls?

**Comment by mukinabis** [comment] 2020-12-25 18:04
Where can I find information? There were no details in the press release.

**Comment by McQgit** [comment] 2020-12-25 18:42
@mukinabis While waiting for IEX to reply (or someone else), you could try their help center:
https://intercom.help/iexcloud/en/collections/2653630-iex-cloud-s-2020-data-migration 
and
https://intercom.help/iexcloud/en/collections/1299541-faqs

**Comment by joshuablackburn-iex** [comment] 2020-12-25 19:38
https://intercom.help/iexcloud/en/articles/4580026-supported-stock-exchanges-on-iex-cloud

**Comment by mukinabis** [comment] 2020-12-25 19:41
@joshuablackburn-iex @McQgit Thank you guys! How do I find out what information is available about companies on these exchanges? Just stock prices or something else?
