### ISSUE TITLE
Company descriptions and other ref data missing/empty

### ISSUE THREAD

**Issue by edmondthui** [iexg/IEX-API#1616] opened 2020-11-29 20:26 UTC
I am trying to display company info on my research page and the description for stock info when using the free IEX API is now 0. This was working last week. 

Example API link:
https://sandbox.iexapis.com/stable/stock/aapl/company?token=Tsk_8c3b99ae9f4b425b81233be1c5e4201b

![image](https://user-images.githubusercontent.com/63014983/100552765-32c13b00-3257-11eb-8a39-1130decc6f4a.png)

**Comment by kristjanmar** [comment] 2020-11-30 11:40
It looks like the descriptions of all stocks in the company endpoint have disappeared, even for paid accounts.

AAPL and TSLA for example both say "description":"" for me.

**Comment by Cyral** [comment] 2020-11-30 13:48
The "name" field for the ref-data/symbols endpoint has also been gone for almost a day now

**Comment by kristjanmar** [comment] 2020-12-01 03:22
There are a bunch of changes in the company endpoint.

Descriptions have returned for me for many (but not all) stocks, but they are all direct copy-pastes from the intro on WikiPedia.

Industries and sectors have also changed, as well as the formatting of the company name, CEO names, ZIP codes, phone number, etc.

**Comment by ikoniaris** [comment] 2020-12-07 01:45
@edmondthui any reason to close this? The problem is still there plus a whole bunch of extra problems that @kristjanmar mentioned above.

**Comment by edmondthui** [comment] 2020-12-07 04:51
Seems like this is still not working for some others. Tim from IEX Cloud reached out to me and it seems to be working for now...

**Comment by rrozenv** [comment] 2020-12-07 14:01
@edmondthui I am still seeing the issue of the description field returning an empty string for certain symbols as of this morning

**Comment by rrozenv** [comment] 2021-01-05 21:50
@timkpaine Is there any update on this issue. Still seeing the description come in as an empty string for a majority of symbols. 

Below is the payload I receive for this URL for example:  `https://cloud.iexapis.com/stable/stock/ADPT/company`

`{
  symbol: 'ADPT',
  companyName: 'Adaptive Biotechnologies Corp',
  exchange: 'NASDAQ/NGS (GLOBAL SELECT MARKET)',
  industry: 'Biological Product (except Diagnostic) Manufacturing ',
  website: 'https://www.adaptivebiotech.com',
  description: '',
  CEO: 'Chad Robins',
  securityName: 'Adaptive Biotechnologies Corp',
  issueType: 'cs',
  sector: 'Manufacturing',
  primarySicCode: 2836,
  employees: null,
  tags: [
    'Commercial Services',
    'Miscellaneous Commercial Services',
    'Manufacturing',
    'Biological Product (except Diagnostic) Manufacturing '
  ],
  address: '1551 Eastlake Ave E Ste 200',
  address2: null,
  state: 'Washington',
  city: 'Seattle',
  zip: '98102-7402',
  country: 'US',
  phone: '12066590067'
}`

**Comment by timkpaine** [comment] 2021-01-05 22:05
@rrozenv no updates but its a known and high priority gap in the data we're looking to close.

**Comment by mfeenstra** [comment] 2021-01-13 21:27
Any update on this?  Still missing descriptions.

**Comment by timpaine-iex** [comment] 2021-01-19 02:08
@mfeenstra the data has to be re-sourced, we're working on it and hopefully can deliver in Q1 or Q2.

**Comment by mfeenstra** [comment] 2021-02-20 08:06
@timpaine-iex I see some of the descriptions coming in now (943 of 9227):
---
```ruby
has_desc = no_desc = 0;
Ticker.all.each do |t|
  unless t.info.description.blank? then
    has_desc += 1
  else
    no_desc += 1
  end
end
puts "With: #{has_desc} Without: #{no_desc}"
```
```
With: 943 Without: 8284
```

**Closed** 2021-08-31 13:45 UTC
Labels: pinned
