### ISSUE TITLE
Feature request - Foreign markets/indices support

### ISSUE THREAD

**Issue by tboooe** [iexg/IEX-API#76] opened 2017-11-10 18:52 UTC
Please consider adding support for foreign markets and indices (FTSE, DAX, Shanghai, etc).  Thank you.

**Comment by codeofsumit** [comment] 2018-04-11 18:44
hi all, love the service. Can you share the progress / problems around this feature?

Keep up the good work 🙏

**Comment by joshuablackburn-iex** [comment] 2018-04-11 18:54
We are definitely working on acquiring new data.  Unfortunately, the process takes a long time, especially to make sure it remains broadly accessible to all of our users.  Indices data is unlikely for the foreseeable future due to prohibitive cost and unfavorable terms.  We are working hard behind the scenes to expand our data, but only where we can keep the API accessible to all.

**Comment by codeofsumit** [comment] 2018-04-12 11:51
@joshuablackburn-iex thank you for taking the time to update me/us on the issue 👍.

**Comment by mmistroni** [comment] 2018-04-18 21:54
any channces to have ability to query stock market indices? e.g. DJI, FTSE  etc?
Also, i am planning to q uery also sectors, such as the ones listed here
https://www.cnbc.com/sectors/

e.g. .SPLRCD

Can i help at all in implementing the feature?
thanks



e.g i want to query

**Comment by evancarter-iex** [comment] 2019-03-07 19:53
Actually a dupe of #51 

Also note, we have Mexico and Canada End of Day data in IEXCloud and will be adding more as we go. 
Https://iexcloud.io

**Closed by evancarter-iex** 2019-03-07 19:53 UTC
Labels: Roadmap: investigating data sources, Roadmap: research required, Type: feature request
