### ISSUE TITLE
Loading never Loads

### ISSUE THREAD

**Issue by MAnthony77** [iexg/IEX-API#1290] opened 2019-10-25 11:01 UTC
I'm new to this type of programming, as I am and Old IBM Mainframer

I am just attempting to obatin a price quote to start and am using
=IMPORTDATA("https://cloud.iexapis.com/stable/stock/"&A5&"/quote/latestPrice?token="&$M$7&"")

However nothing ever loads, the cell continously just states "loading"

**Comment by MorningSleeper** [comment] 2019-10-27 05:43
That is a common error on external requests in Google sheets that likely has nothing to do with the source being requested but issues related to Google itself or your sheet. You can try to delete formula and readd it to force it to try again or longer term add a reference to a cell in the formula that is updated by apps script on a 5 minute trigger to force the formula to update.

While likely not the cause of the problem, you should also be aware that IMPORTDATA is for importing files in csv or tsv format, the default IEX format is JSON, try adding format=csv to URL to specify csv format.

[https://support.google.com/docs/answer/3093335?hl=en](https://support.google.com/docs/answer/3093335?hl=en)

[https://iexcloud.io/docs/api/#data-formats](https://iexcloud.io/docs/api/#data-formats)

**Comment by MorningSleeper** [comment] 2019-10-27 05:56
That is a common error on external requests in Google sheets that likely has nothing to do with the source being requested but issues related to Google itself or your sheet. You can try to delete formula and readd it to force it to try again or longer term add a reference to a cell in the formula that is updated by apps script on a 5 minute trigger to force the formula to update. I tested the URL you provided and it worked fine.

**Comment by evancarter-iex** [comment] 2019-10-28 14:46
Thanks @MorningSleeper.

I'm going to close this since its a google sheets error, not our side.

**Closed by evancarter-iex** 2019-10-28 14:46 UTC
Labels: IEX Cloud, Type: issue
