### ISSUE TITLE
Dividend Yield missing for most securities

### ISSUE THREAD

**Issue by HeadWrench** [iexg/IEX-API#966] opened 2019-05-20 01:09 UTC
With the old api I could usually get about a 90% success rate for pulling Dividend Yield data, for stocks, preferreds, traded funds, and even some babybonds. Wasn't that great - but now we've gone backwards with your new data provider.
With the new cloud api that has dropped to around 50%. Mostly it is the traded funds, preferreds, and baby bonds that don't return the yield data. And even then some of the numbers are off, and a few are grossly wrong.
A typical request:
https://cloud.iexapis.com/stable/stock/KBWY/stats/dividendYield
Can the sunset be postponed for the old api, until the provider can supply this basic data?

**Comment by evancarter-iex** [comment] 2019-05-20 13:39
@HeadWrench  Thanks, this is a dupe of #855 We are working through an integration with our data provider for additional information on ADRs and ETFs.

Unfortunately, we cannot delay the sunsetting of the old API.

**Closed by evancarter-iex** 2019-05-20 13:39 UTC
