### ISSUE TITLE
Historical Prices (chart) endpoint in IEX Cloud beta does not adjust for dividends

### ISSUE THREAD

**Issue by lgellert** [iexg/IEX-API#691] opened 2019-02-17 19:31 UTC
## Summary

The IEX Cloud Historical Prices (chart) endpoint is returning unadjusted values. It is not accounting for regular dividends. In addition the field `Close` matches `uClose` which is confusing. 

## Details

The old IEX Trading Chart API data adjusts for dividends so the 'close price' is lower in the past to account for that. The new IEX Cloud Historical Data endpoint (beta) does not include these regular dividends. 

This appears to be happening to any ETF with a regular dividend. The three I've confirmed are AGG, BND, BNDX.

Also, the uClose field matches Close no matter what which is confusing.

### Date/time of issue

2/17/19 10:30am PST

### API URL

IEX Cloud URL:
https://cloud.iexapis.com/beta/stock/AGG/chart/1y?token={token}

The old live IEX Trading Chart API returns adjusted values.
https://api.iextrading.com/1.0/stock/AGG/chart/1y

### What you expected to happen

I would expect IEX Cloud Historical Data 'Close' field to match IEX Trading Chart data and account for regular dividends, with the uClose field being the unadjusted close.

### What actually happened

IEX Cloud Historical data does not account for regular dividends.  The field uClose (unadjusted close?) always matches Close?

### Other Information (sample code, links, etc.)

Similar topic was discussed in #496, advocating to remove regular dividends from the Historical Data feed. Did that actually happen?  Seems like you can't make everybody happy and need to provide data in both adjusted and unadjusted formats.  Some people want the raw price data, others want total return including dividends.  Yahoo finance does the former, stock charts does the latter...

If there was a field for unadjusted close that was different from close (adjusted close) then that would work for both groups. Or setup an input parameter for adjusted={true/false}.

Is that what the `uClose` field is supposed to be for?

**Comment by joshuablackburn-iex** [comment] 2019-02-19 18:33
uClose represents the unadjusted close. (https://iexcloud.io/docs/api/#historical-prices)

We will look into ETFs.

**Comment by joshuablackburn-iex** [comment] 2019-02-20 11:33
I checked with our provider and historical data is adjusted for splits only. We will apply dividend adjustments to previous day close prices, but we are not able to adjust historical prices at this time. We are working with our dividend data provider to expand our history from 5 years to 12 years. If we are able to get the extra data, we can provide an additional value in historical data for split+dividend adjustments, but only up to 12 years back.

**Comment by lgellert** [comment] 2019-02-20 17:20
Thank you for the update.

**Comment by stockenja** [comment] 2019-06-05 04:09
Dear @joshuablackburn-iex 

I am surprised that you guys would have switched over to provider without noticing that they did not include dividend in the adjusted price.

Especially with IEX Cloud now is only semi-free, I expect quality to go up. In fact, this is such an important feature that  I feel that your team should implement this feature yourself. This issue is causing a huge headache for my application... 

I really hope it gets resolve soon without breaking more stuff.

My question would be - should I go on ahead and adjust the dividend myself and will you guarantee the same behavior so that I don't have to go resolve it again? Or is there an API version so that I don't have keep fixing stuff as your API changes?

**Comment by edwin177** [comment] 2019-06-18 06:38
I'm really surprised this was not resolved before IEX Trading Chart data was sunset last week. Is IEX Cloud not using the same data provider as IEX Trading for historical prices?

**Comment by dugwood** [comment] 2019-11-08 06:40
@jonathanyam-iex do we have any option for this? A lot of charts' studies are based on dividends adjusted prices.

**Comment by ThaiDangFr** [comment] 2020-03-11 13:30
Hello, the problem is still not fixed. Is there any workaround ? It is still unusable as is.

**Comment by dwhitney** [comment] 2020-03-17 17:03
also your advanced_splits endpoint isn't serving up any data: 

https://cloud.iexapis.com/v1/time-series/advanced_splits/afl?range=5y&token=<token>
while the basic is:
https://cloud.iexapis.com/v1/stock/afl/splits/5y?token=<token>

However, the basic split doesn't work with longer ranges, like 12y.

Please fix this. Thanks!

**Comment by MorningSleeper** [comment] 2020-03-17 18:08
@dwhitney FYI, the basic splits endpoint does not work for short term ranges either for many symbols as reported in https://github.com/iexg/IEX-API/issues/1330

**Comment by arozenv** [comment] 2020-10-31 02:32
When doing any serious work on mutual fund analysis, one needs dividend & split adjusted prices. Can someone from IEX cloud comment on this? Any idea if this is in the plans to develop? Any sample code available where one can get closing price + dividend = adjusted close?

**Comment by birinoah** [comment] 2021-03-27 18:53
Would love this issue to get fixed - has anyone tried manually incorporating the dividend data? Was thinking about trying that.

**Comment by joshuablackburn-iex** [comment] 2021-03-27 18:55
Our historical price data includes unadjusted, dividend adjusted, and dividend+split adjusted.

**Closed** 2021-03-27 18:55 UTC
Labels: IEX Cloud, Type: data

**Comment by birinoah** [comment] 2021-03-27 19:10
I'm pretty new to this, would anyone mind helping me out? Which field from the historical prices endpoint is split+dividend adjusted? I'm guessing the basic "close" but wanted to confirm

**Comment by lgellert** [comment] 2021-03-27 19:16
@birinoah I believe you want `fClose`.  

See: https://iexcloud.io/docs/api/#historical-prices

**Comment by birinoah** [comment] 2021-03-27 19:18
Thank you! @lgellert
