### ISSUE TITLE
[Data] Quote queries return null for open, low, high, close, latestVolume, volume and all "extended..." fields

### ISSUE THREAD

**Issue by apankrat** [iexg/IEX-API#1556] opened 2020-08-18 13:02 UTC
**Clearly describe the data problem**

As per description, a response to a basic query like this -

https://cloud.iexapis.com/stable/stock/market/batch?symbols=AAPL&types=quote&token=<snip>

contains a lot of nulls. In particular, `open`, `openTime`, `close`, `closeTime`, `high`, `low`, **`latestVolume`** (!) and all `extended...` fields are nulls. Oddly enough, `lowTime` and `highTime` are *not* nulls and carry what appears to be valid timestamps.

Here's a sample response:

`{"AAPL":{"quote":{"symbol":"AAPL","companyName":"Apple, Inc.","primaryExchange":"NASDAQ","calculationPrice":"close","open":null,"openTime":null,"openSource":"official","close":null,"closeTime":null,"closeSource":"official","high":null,"highTime":1597708797763,"highSource":"15 minute delayed price","low":null,"lowTime":1597679217410,"lowSource":"15 minute delayed price","latestPrice":458.43,"latestSource":"Close","latestTime":"August 17, 2020","latestUpdate":1597694400358,"latestVolume":null,"iexRealtimePrice":0,"iexRealtimeSize":0,"iexLastUpdated":0,"delayedPrice":null,"delayedPriceTime":null,"oddLotDelayedPrice":null,"oddLotDelayedPriceTime":null,"extendedPrice":null,"extendedChange":null,"extendedChangePercent":null,"extendedPriceTime":null,"previousClose":459.63,"previousVolume":41391302,"change":-1.2,"changePercent":-0.00261,"volume":null,"iexMarketPercent":null,"iexVolume":0,"avgTotalVolume":39958589,"iexBidPrice":450,"iexBidSize":200,"iexAskPrice":0,"iexAskSize":0,"iexOpen":null,"iexOpenTime":null,"iexClose":458.75,"iexCloseTime":1597694394959,"marketCap":1960077060900,"peRatio":34.54,"week52High":464.35,"week52Low":199.67,"ytdChange":0.54489,"lastTradeTime":1597694399990,"isUSMarketOpen":false}}}`

**Data URL (The URL you used to access the data without your token):**

https://cloud.iexapis.com/stable/stock/market/batch?symbols=AAPL&types=quote&token=<snip>

**What time did the problem occur (including timezone)?**

2020-08-17 09:30 through 2020-08-18 09:00 EST, i.e. during the pre-market, open market, after market periods.

**What is the expected behavior?**

Either get a valid data or see some sort of explanation in the docs if there are any restrictions, caveats or some such.

**What are the steps to reproduce**

Pull on the above URL using a free tier token.

**Your environment (e.g. browser, OS, API version, language):**

Recent Firefox, not that it should matter at all.

**Additional context**

The same applies to the sandbox queries, **but** I am all but certain that they used to return proper (non-null) values last week and through this weekend. The change in behavior appears to have happened on Sunday/Monday.

**Comment by unozerocode** [comment] 2020-09-04 16:05
We are seeing similar problems in a different API call, will add them to this issue because the main issue is undocumented behavior.

**Clearly describe the data problem**

The data returned by the API does not match the documentation.
When calling https://sandbox.iexapis.com/stable/time-series in order to retrieve available time series, according to the documentation we should be seeing data in this format:

```
{
  "id": "REPORTED_FINANCIALS",
  "description": "Reported financials",
  "key": "a valid symbol",
  "subkey": "10-K,10-Q",    
  "schema": {
    "type": "object",
    "properties": {
      "formFiscalYear": {
        "type": "number"
      },
      "formFiscalQuarter": {
        "type": "number"
      },
      "version": {
        "type": "string"
      },
      "periodStart": {
        "type": "string"
      },
      "periodEnd": {
        "type": "string"
      },
      "dateFiled": {
        "type": "string"
      },
      "reportLink": {
        "type": "string"
      },
      "adsh": {
        "type": "string"
      },
      "stat": {
        "type": "object"
      }
    }
  },
  "weight": 5000,
  "created": "2019-06-04 21:32:20",
  "lastUpdated": "2019-06-04 21:32:20"
}
```

But the data returned is in this format:

```
[{
   "inv_pk":8,
   "id":"FX",
   "description":"xa5i Se tao,ePrs ahspdoiro cnr t2 la,ftri",
   "schema":{
      "additionalProperties":true,
      "properties":{
         "rate":{
            "type":"number"
         },
         "symbol":{
            "type":"string"
         },
         "timestamp":{
            "type":"number"
         }
      },
      "required":[
         "tmsitaemp",
         "tare"
      ],
      "type":"object"
   },
   "weight":102738,
   "created":"2020-05-05T16:58:52.000Z",
   "updated":"2020-05-05T16:58:52.000Z",
   "version":1,
   "weightKey":"FX"
}(truncated)
```

As can be seen here, the properties field contains completely different data than what the document states, for example the document calls out "formFiscalYear", "formFiscalQuarter", "version", etc, and yet the response contains none of those, and contains other undocumented fields such as "rate", "symbol", "timestamp". 
When we coded to the specification of the documentation, the response could not be parsed correctly because it has a completely different shape.
We require that the response match the specification otherwise the data cannot be correctly interpreted or persisted to our local database, what is the authoritative source of truth for the data we should be seeing coming back from the platform? 

**Data URL (The URL you used to access the data without your token):**
 https://sandbox.iexapis.com/stable/time-series

**What time did the problem occur (including timezone)?**
week of Friday, September 4, 2020 (CDT)

**What is the expected behavior?**

To return data in the documented format.

**What are the steps to reproduce:**

Pull on the above URL using a free tier token.

**Your environment (e.g. browser, OS, API version, language):**
Chrome, Windows 10, API version: 1, Language: Elixir

**Comment by joshuablackburn-iex** [comment] 2020-09-04 16:47
Please take a look at our documentation again and see where we explain that nasdaq UTP requires our users to sign an agreement with them to get some data, essentially the nulls you point out. The data that is not null is because IEX does not charge for market data, so we fill in where that data is available.

**Comment by joshuablackburn-iex** [comment] 2020-09-04 16:49
@unozerocode the data you reference is the schema for reported financials, not the financials themselves.

**Comment by unozerocode** [comment] 2020-09-04 21:48
Taking into account what you have pointed out, at the very least we have confusing documentation.
![image](https://user-images.githubusercontent.com/57536442/92286059-92fc4700-eecb-11ea-9e00-b6816d012143.png)
It looks like the tech writer omitted the JSON-RESPONSE section for GET /time-series/, then placed the JSON-RESPONSE  to GET/time-series/{id}, directly below GET /time-series, when it should have gone a paragraph later below the HTTP-REQUEST GET /time-series/{id}.
So aside from the mixed-up sections, we are missing the specification for JSON-RESPONSE to GET /time-series.

**Comment by timpaine-iex** [comment] 2020-12-16 16:05
closing, this is well documented

**Closed by timpaine-iex** 2020-12-16 16:05 UTC
Labels: IEX Cloud, Type: data
