### ISSUE TITLE
Financials - More than past 4 quarters 

### ISSUE THREAD

**Issue by abhijitshingote** [iexg/IEX-API#433] opened 2018-07-22 14:30 UTC
## Summary
Are there any plans to include financials for more than past 4 quarters. If yes, when and how far back?

**Comment by icastillejogomez** [comment] 2018-07-23 18:51
I need it too :/

**Comment by evancarter-iex** [comment] 2018-07-23 19:07
Duplicate of #339

**Closed by evancarter-iex** 2018-07-23 19:07 UTC
