### ISSUE TITLE
[Data] Excess dividends datapoint for AAPL on the split date

### ISSUE THREAD

**Issue by EugeneKostrikov** [iexg/IEX-API#1610] opened 2020-11-15 20:42 UTC
### Please keep all posted issues professional and constructive. We may delete posts that do not provide sufficient information, are outright negative and unproductive, or are not directly related to IEX Cloud.

**Clearly describe the data problem**
There's an excess datapoint for AAPL dividends (basic endpoint). To add more, the value is an empty string :)  Looks like something to do with the split, it happened the same day. 
```
{
        "exDate": "2020-08-31",
        "paymentDate": "2020-08-28",
        "recordDate": "2020-08-24",
        "declaredDate": "2020-07-30",
        "amount": "",
        "flag": "Stock",
        "currency": "",
        "description": "Ordinary Shares",
        "frequency": "quarterly",
        "date": "2020-11-15"
    }
```
**Data URL (The URL you used to access the data without your token):**
https://cloud.iexapis.com/v1/stock/AAPL/dividends/6m

**What time did the problem occur (including timezone)?**
2020-11-15T20:33:00Z

**What is the expected behavior?**
Expected not to have a fake datapoint

**What are the steps to reproduce**
Send a GET request to the endpoint above. Also reproduces on any other period that includes 2020-08-31 exDate.

**Your environment (e.g. browser, OS, API version, language):**
Browser

**Additional context**
According to the docs, the dividends amount a number, but it's actually a string. Not sure if it's reported elsewhere. Not a big deal to workaround anyway.

**Comment by timpaine-iex** [comment] 2020-12-21 17:26
duplicate of #1603

**Closed by timpaine-iex** 2020-12-21 17:26 UTC
Labels: IEX Cloud, Type: data
