### ISSUE TITLE
Websockets not working

### ISSUE THREAD

**Issue by pimentahodl** [iexg/IEX-API#566] opened 2018-11-21 01:58 UTC
## Summary

I tried your websockets example and it's not working. Sockets don't even connect.

## Details

Tried connecting with socket io, followed your example and also tried other endpoints, and the socket does not connect.

### Date/time of issue

20th November 2018

### API URL

https://ws-api.iextrading.com/1.0/tops and other ws endpoints

### What you expected to happen

Get a message or at least get inside connect event.

### What actually happened

Did not connect nor receive message.

### Other Information (sample code, links, etc.)

Example I followed that did not work:

```
// Import socket.io with a connection to a channel (i.e. tops)
const socket = require('socket.io-client')('https://ws-api.iextrading.com/1.0/tops')

// Listen to the channel's messages
socket.on('message', message => console.log(message))

// Connect to the channel
socket.on('connect', () => {

  // Subscribe to topics (i.e. appl,fb,aig+)
  socket.emit('subscribe', 'snap,fb,aig+')

  // Unsubscribe from topics (i.e. aig+)
  socket.emit('unsubscribe', 'aig+')
})

// Disconnect from the channel
socket.on('disconnect', () => console.log('Disconnected.'))
```

**Comment by thatcampbellkid** [comment] 2018-11-21 02:41
I haven't been able to get it to work the last two days either... must be getting ready for 2.0

**Comment by evancarter-iex** [comment] 2018-11-23 18:36
Dupe of #564

**Closed by evancarter-iex** 2018-11-23 18:36 UTC
