### ISSUE TITLE
WebSocket received same data!

### ISSUE THREAD

**Issue by Cartman720** [iexg/IEX-API#174] opened 2018-01-11 17:18 UTC
## Summary

WebSocket received same data again and again for same stock, though there is only few peers connected (NOTE that on local)

## Details

Here the image of my console logs.

![image](https://user-images.githubusercontent.com/12465135/34837599-bc16bc6c-f714-11e7-8844-202efa37e9bf.png)

**UPDATE**

Here the log after few minutes ago

![image](https://user-images.githubusercontent.com/12465135/34838216-c2bbe77a-f716-11e7-9c2a-23225cceeaa9.png)

# here my code

I put some testing code to see how many subscribers I have for same stock and frequency of same data.

```
let prevMessage = '';
	let connectedPeers = 0;

	iex.on('message', message => {
		let { symbol, lastSalePrice, lastSaleSize, lastSaleTime, lastUpdated } = JSON.parse(message);

		if (symbol == 'TSLA') {
			console.log(`Time: ${new Date()}, Peers: ${connectedPeers}`, message == prevMessage);

			prevMessage = message;
		}

		if (lastUpdated && lastUpdated > -1) {
			io.emit(symbol, {
				price: lastSalePrice,
				size: lastSaleSize,
				timestamp: lastSaleTime
			});
		}
	});

	io.on('connection', socket => {
		socket.on('symbol price', symbol => {
			if (symbol == 'TSLA') {
				connectedPeers++
			}

			iex.emit('subscribe', symbol);
		});
	});
```

Please let me know what is going on.

**Comment by joshuablackburn-iex** [comment] 2018-01-17 16:19
Currently Websockets will return the latest snapshot data which can be a duplicate of previously sent data.  This is something we are addressing for v2.  We will dedupe data and stream it via SSE.

**Closed by joshuablackburn-iex** 2018-01-17 16:19 UTC
Labels: Type: question
