### ISSUE TITLE
data available?

### ISSUE THREAD

**Issue by Amosss** [iexg/IEX-API#737] opened 2019-03-02 16:15 UTC
While old API has data for ETFs dividend history, the new API returns empty data, for example bdcl, spy, sdy. Is it known?

I didn't find the following information in the new APIs:
price_earning
price_book
return_equity
forward_price_earning
payout_ratio
growth1y
growth3y
growth5y
growth10y
estimate5growth
past5growth
debt_equity
Beta
---
div announcements (not paid yet)
---
Is it available maybe in different names?
Thanks

**Comment by Amosss** [comment] 2019-03-02 16:16
Sorry for the styling, I didn't find a way to remove it. Even copy/paste using notepad didn't help.

**Comment by evancarter-iex** [comment] 2019-03-04 15:53
Dupe of #715

**Closed by evancarter-iex** 2019-03-04 15:53 UTC

**Comment by Amosss** [comment] 2019-03-04 16:21
The other discussion is a request regarding dividends, my question has no relation to dividends and now it is closed with no apparent reason.... @evancarter-iex

**Comment by evancarter-iex** [comment] 2019-03-04 17:56
Correction. This is a dupe of #654

**Comment by Amosss** [comment] 2019-03-04 19:50
What about this part?
I didn't find the following information in the new APIs:
price_earning
price_book
return_equity
forward_price_earning
payout_ratio
growth1y
growth3y
growth5y
growth10y
estimate5growth
past5growth
debt_equity
Beta

Thanks

**Comment by evancarter-iex** [comment] 2019-03-04 19:52
I see, the way this request was submitted, made it very hard to understand. For those can you open a new ticket (since this one is very hard to read with everything bolded).
