### ISSUE TITLE
Support real-time quote of indexes (SPX, VIX, etc.)

### ISSUE THREAD

**Issue by zxcvbn97** [iexg/IEX-API#102] opened 2017-11-22 08:01 UTC
## Summary
Support real-time quote of indexes (SPX, VIX, etc.)

### What you expected to happen
API real-time quote of indexes, e.g., `https://api.iextrading.com/1.0/stock/market/batch?symbol=SPX`

**Comment by DawBin** [comment] 2017-11-22 13:30
Looking for working examples of this service?

**Comment by evancarter-iex** [comment] 2017-11-22 14:20
Closing as duplicate of https://github.com/iexg/IEX-API/issues/36 . As stated in that question:

```
We do not have quotes for indices. The closest we have are the tracking ETFs (SPY, DIA, IWM, etc). Indices data is not a distributable product, and requires agreements directly with the index data provider.
```

**Closed by evancarter-iex** 2017-11-22 14:20 UTC
Labels: Resolution: duplicate, Type: question
