### ISSUE TITLE
[Data] SQQQ split today

### ISSUE THREAD

**Issue by hmTodd** [iexg/IEX-API#979] opened 2019-05-24 14:09 UTC
**Clearly describe the data problem**
The ETF SQQQ split today, a reverse split 1 for 4.  This is missing from the /splits request.  It is also missing from the upcoming-events request.  

**Data URL (The URL you used to access the data without your token):**
https://cloud.iexapis.com/beta/stock/sqqq/splits/1m?
https://cloud.iexapis.com/beta/stock/sqqq/splits/next?

**What time did the problem occur (including timezone)?**
9:00 am CT

**What is the expected behavior?**

**What are the steps to reproduce**

**Your environment (e.g. browser, OS, API version, language):**

**Additional context**

**Comment by evancarter-iex** [comment] 2019-05-24 14:30
Dupe of #869.

**Closed by evancarter-iex** 2019-05-24 14:30 UTC
Labels: IEX Cloud, Type: data
