### ISSUE TITLE
Where to get symbols that have been delisted or merged?

### ISSUE THREAD

**Issue by jesseorosz** [iexg/IEX-API#599] opened 2018-12-26 16:03 UTC
## Summary
I'd like to get a list of symbols that have been delisted, merged
https://api.iextrading.com/1.0/ref-data/symbols only returns current symbols

## Details
Would like to have a date parameter in https://api.iextrading.com/1.0/ref-data/symbols
*AET does not appear in this list

### Date/time of issue
12/26/18

### API URL
https://api.iextrading.com/1.0/ref-data/symbols

### What you expected to happen

https://api.iextrading.com/1.0/ref-data/symbols to have date parameter or another URL that has a list of changes

**Comment by noam2** [comment] 2019-10-30 20:13
any update on this ???

**Comment by timpaine-iex** [comment] 2021-03-01 16:27
duplicate of https://github.com/iexg/IEX-API/issues/206

**Closed by timpaine-iex** 2021-03-01 16:27 UTC
Labels: IEX Cloud, Resolution: moving to IEX Cloud, Type: feature request
