### ISSUE TITLE
[Request]

### ISSUE THREAD

**Issue by speedyb0y** [iexg/IEX-API#1158] opened 2019-08-01 02:25 UTC
**Is your feature request related to a problem? Please describe.**
Asking for multiple quotes returns error message if one of them does not exist.

**Describe the solution you'd like**

If we ask for multiple quotes, the correct behavior would me to return the error messages only for the symbols not found; the other ones should return normally.

https://cloud.iexapis.com/beta/stock/market/quote?token=MY_TOKEN&symbols=VALE,PBR,SID,DONTEXIST

Response:
{ "symbol": "VALE", ... }
{ "symbol": "DONTEXIST", "error":  "Symbol not found" }
{ "symbol": "PBR ... }

**Describe alternatives you've considered**

Even better, it could just ignore the symbols not found, and return nothing at all for them.

**Additional context**

**Comment by speedyb0y** [comment] 2019-08-01 23:14
To deal with this problem, my current approach is:
- Get every day the current list of all symbols
- Make 1 request for each symbol

Because I can't use the batch requests because if a single symbol has been removed, the other 99 ones won't get updated and I will have no idea which one was removed. (and updating symbols list again costs too much credits)

This is a problem for the user and also for IEX Cloud, because of the overhead of 1 request/symbol.

**Comment by evancarter-iex** [comment] 2019-11-03 01:04
Dupe of #956

**Closed by evancarter-iex** 2019-11-03 01:04 UTC
Labels: IEX Cloud, Type: enhancement request
