### ISSUE TITLE
Will the API support foreign markets like Canada

### ISSUE THREAD

**Issue by djoron** [iexg/IEX-API#98] opened 2017-11-19 21:45 UTC
Good day,

First thanks for developping such an API ! I was wondering, will foreign markets eventually be supported ? I live in Canada so that would be the first I'm interested in (TSX - Toronto Stock Exchange). Request similar to issue #76. Note the same symbol name can appear between markets unless you add a suffix (ex: CAE on US market vs CAE.to on Toronto Stock exchange).

Thank you !

Dominic

**Comment by djoron** [comment] 2017-11-19 21:47
Similar to issue #76 .

**Comment by evancarter-iex** [comment] 2017-11-20 14:27
Duplicate of #76. Closing this.

**Closed by evancarter-iex** 2017-11-20 14:27 UTC
Labels: Resolution: duplicate, Roadmap: investigating data sources, Type: enhancement
