### ISSUE TITLE
Request add Mutual fund info

### ISSUE THREAD

**Issue by clovett** [iexg/IEX-API#232] opened 2018-02-19 02:21 UTC
## Summary

I love your API, this [stock quote API ](https://api.iextrading.com/1.0/stock/market/batch?symbols=aapl,fb&types=quote&range=1m&last=1) seems really snappy.

But it is not finding any of my Mutual Funds, For example, the following symbol: **LCEYX**.  I'm guess it is because those are not stocks.  So do you have any plans to add an API for mutual funds?  If so, that would be awesome.

**Comment by joshuablackburn-iex** [comment] 2018-02-20 11:29
It's on our roadmap, but I do not have a definitive date.

**Comment by evancarter-iex** [comment] 2018-02-22 14:21
Duplicate of https://github.com/iexg/IEX-API/issues/16

**Closed by evancarter-iex** 2018-02-22 14:21 UTC
Labels: Roadmap: backlog, Type: data, Type: enhancement request
