### ISSUE TITLE
High and Low on Quote?

### ISSUE THREAD

**Issue by logikonline** [iexg/IEX-API#82] opened 2017-11-13 15:14 UTC
Is there a reason you do not high and low on the quote?  This is very important.

**Comment by yccheok** [comment] 2017-11-13 17:31
Hi @logikonline , the same request has been submitted : https://github.com/iexg/IEX-API/issues/46

**Comment by jcape** [comment] 2017-11-13 18:38
Closing as duplicate of #46

**Closed by jcape** 2017-11-13 18:38 UTC
