### ISSUE TITLE
[Data] cmcsa, dis dividend history is incorrect

### ISSUE THREAD

**Issue by JamesChloroBenzene** [iexg/IEX-API#1466] opened 2020-05-04 14:41 UTC
**Clearly describe the data problem**
1. CMCSA: dividend amount is null, guess it is trash value.
{"exDate":"2017-02-21","paymentDate":"2017-02-17","recordDate":"2017-02-08","declaredDate":"2017-01-24","amount":"","flag":"Stock","currency":"","description":"Ordinary Shares - Class A","frequency":null,"date":"2020-05-04"}

2. DIS: dividend history only show recent 2 years, though there are lot more history
[{"exDate":"2019-12-13","paymentDate":"2020-01-16","recordDate":"2019-12-16","declaredDate":"2019-12-04","amount":"0.88","flag":"Cash","currency":"USD","description":"Ordinary Shares","frequency":"semi-annual","date":"2020-05-04"},{"exDate":"2019-07-05","paymentDate":"2019-07-25","recordDate":"2019-07-08","declaredDate":"2019-06-26","amount":"0.88","flag":"Cash","currency":"USD","description":"Ordinary Shares","frequency":"semi-annual","date":"2020-05-04"}]

**Data URL (The URL you used to access the data without your token):**
1. https://cloud.iexapis.com/stable/stock/cmcsa/dividends?range=5y
2. https://cloud.iexapis.com/stable/stock/dis/dividends?range=5y

**What time did the problem occur (including timezone)?**
Always

**What is the expected behavior?**
Plz fix the issue

**What are the steps to reproduce**
1. https://cloud.iexapis.com/stable/stock/cmcsa/dividends?range=5y
2. https://cloud.iexapis.com/stable/stock/dis/dividends?range=5y

**Your environment (e.g. browser, OS, API version, language):**
Always

**Additional context**

**Comment by timpaine-iex** [comment] 2021-04-28 22:36
dupe of https://github.com/iexg/IEX-API/issues/1359

**Closed by timpaine-iex** 2021-04-28 22:36 UTC
Labels: IEX Cloud, Type: data
